# Generated by Django 4.1.1 on 2022-11-28 14:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField(auto_now_add=True)),
                ('titulo_evento', models.CharField(max_length=100)),
                ('desarrollo_evento', ckeditor.fields.RichTextField()),
                ('imagen_evento', models.ImageField(null=True, upload_to='media/evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_noticia', models.DateField(auto_now_add=True)),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('desarrollo_noticia', ckeditor.fields.RichTextField()),
                ('imagen_noticia', models.ImageField(null=True, upload_to='media/noticia')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
