# Generated by Django 4.1.1 on 2022-10-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_eventos_desarrollo_evento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
